# Generated by Django 4.2.25 on 2026-03-05 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Numero de telefono con codigo de pais (ej. +573001234567)",
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Numero de telefono",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cedula de Ciudadania"),
                            ("CE", "Cedula de Extranjeria"),
                            ("TI", "Tarjeta de Identidad"),
                            ("NIT", "NIT"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        default="CC",
                        max_length=10,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=20, verbose_name="Numero de documento"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Apellidos"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electronico",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario ha verificado su numero de telefono.",
                        verbose_name="Verificado",
                    ),
                ),
                (
                    "is_merchant",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario es un comerciante registrado.",
                        verbose_name="Es comerciante",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Ciudad"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualizacion"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="Codigo OTP")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("REGISTER", "Registro"),
                            ("LOGIN", "Inicio de sesion"),
                            ("TRANSFER", "Transferencia"),
                            ("RESET", "Restablecer contrasena"),
                        ],
                        max_length=10,
                        verbose_name="Proposito",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="Fecha de expiracion"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Usado")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Codigo OTP",
                "verbose_name_plural": "Codigos OTP",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cedula de Ciudadania"),
                            ("CE", "Cedula de Extranjeria"),
                            ("TI", "Tarjeta de Identidad"),
                            ("NIT", "NIT"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "front_image",
                    models.ImageField(
                        upload_to="kyc/front/", verbose_name="Imagen frontal"
                    ),
                ),
                (
                    "back_image",
                    models.ImageField(
                        upload_to="kyc/back/", verbose_name="Imagen trasera"
                    ),
                ),
                (
                    "selfie_image",
                    models.ImageField(upload_to="kyc/selfie/", verbose_name="Selfie"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de revision"
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Notas del revisor"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento KYC",
                "verbose_name_plural": "Documentos KYC",
                "ordering": ["-created_at"],
            },
        ),
    ]
