# Generated by Django 5.1.5 on 2026-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                default="CO",
                help_text="Codigo ISO 3166-1 alpha-2 (CO, US, MX, etc)",
                max_length=2,
                verbose_name="Pais (ISO)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_currency",
            field=models.CharField(
                blank=True, default="COP", max_length=3, verbose_name="Moneda preferida"
            ),
        ),
    ]
