# Generated by Django 4.2.25 on 2026-03-05 19:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_limit_cop",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000000.00"),
                        max_digits=15,
                        verbose_name="limite diario COP",
                    ),
                ),
                (
                    "monthly_limit_cop",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20000000.00"),
                        max_digits=15,
                        verbose_name="limite mensual COP",
                    ),
                ),
                (
                    "per_transaction_limit_cop",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2000000.00"),
                        max_digits=15,
                        verbose_name="limite por transaccion COP",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_limit",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "limite de transferencia",
                "verbose_name_plural": "limites de transferencia",
            },
        ),
        migrations.CreateModel(
            name="ScheduledTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("COP", "Peso colombiano"), ("LLO", "LlanoCoin")],
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diaria"),
                            ("WEEKLY", "Semanal"),
                            ("BIWEEKLY", "Quincenal"),
                            ("MONTHLY", "Mensual"),
                        ],
                        max_length=10,
                        verbose_name="frecuencia",
                    ),
                ),
                (
                    "next_execution_date",
                    models.DateField(verbose_name="proxima fecha de ejecucion"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descripcion"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_transfers_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatario",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "transferencia programada",
                "verbose_name_plural": "transferencias programadas",
                "ordering": ["next_execution_date"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("COP", "Peso colombiano"), ("LLO", "LlanoCoin")],
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="monto de comision",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=5,
                        verbose_name="tasa de comision",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descripcion"
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="referencia",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("OTP_REQUIRED", "Requiere OTP"),
                            ("COMPLETED", "Completada"),
                            ("FAILED", "Fallida"),
                            ("REVERSED", "Reversada"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="estado",
                    ),
                ),
                (
                    "otp_verified",
                    models.BooleanField(default=False, verbose_name="OTP verificado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de completado"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatario",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "transferencia",
                "verbose_name_plural": "transferencias",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "created_at"],
                        name="idx_transfer_sender_created",
                    ),
                    models.Index(
                        fields=["receiver", "created_at"],
                        name="idx_transfer_receiver_created",
                    ),
                ],
            },
        ),
    ]
