# Generated by Django 4.2.25 on 2026-03-05 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=200, verbose_name="nombre del negocio"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descripcion"
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="direccion")),
                ("city", models.CharField(max_length=100, verbose_name="ciudad")),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("META", "Meta"),
                            ("CASANARE", "Casanare"),
                            ("ARAUCA", "Arauca"),
                            ("VICHADA", "Vichada"),
                            ("GUAINIA", "Guainia"),
                            ("GUAVIARE", "Guaviare"),
                            ("VAUPES", "Vaupes"),
                        ],
                        max_length=10,
                        verbose_name="departamento",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitud",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitud",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="telefono")),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="whatsapp"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="marketplace/logos/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="marketplace/covers/",
                        verbose_name="imagen de portada",
                    ),
                ),
                (
                    "accepts_llo",
                    models.BooleanField(default=True, verbose_name="acepta LLO"),
                ),
                (
                    "accepts_cop",
                    models.BooleanField(default=True, verbose_name="acepta COP"),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=5,
                        verbose_name="tasa de comision (%)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verificado"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="calificacion",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="total de resenas"),
                ),
                (
                    "total_sales",
                    models.IntegerField(default=0, verbose_name="total de ventas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "comerciante",
                "verbose_name_plural": "comerciantes",
                "ordering": ["-rating", "-total_sales"],
            },
        ),
        migrations.CreateModel(
            name="MerchantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre del icono (ej. mdi-store, fa-shop)",
                        max_length=50,
                        verbose_name="icono",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descripcion"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                ("order", models.IntegerField(default=0, verbose_name="orden")),
            ],
            options={
                "verbose_name": "categoria de comerciante",
                "verbose_name_plural": "categorias de comerciantes",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titulo")),
                ("description", models.TextField(verbose_name="descripcion")),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="porcentaje de descuento",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="monto de descuento",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="fecha de inicio")),
                ("end_date", models.DateTimeField(verbose_name="fecha de fin")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="marketplace/promotions/",
                        verbose_name="imagen",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="marketplace.merchant",
                        verbose_name="comerciante",
                    ),
                ),
            ],
            options={
                "verbose_name": "promocion",
                "verbose_name_plural": "promociones",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="MerchantPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("COP", "Peso colombiano"), ("LLO", "LlanoCoin")],
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="monto de comision",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="referencia"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descripcion"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de completado"
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="marketplace.merchant",
                        verbose_name="comerciante",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pagador",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago a comerciante",
                "verbose_name_plural": "pagos a comerciantes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="merchant",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merchants",
                to="marketplace.merchantcategory",
                verbose_name="categoria",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchant_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.CreateModel(
            name="MerchantReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="calificacion",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="comentario"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="marketplace.merchant",
                        verbose_name="comerciante",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "resena de comerciante",
                "verbose_name_plural": "resenas de comerciantes",
                "ordering": ["-created_at"],
                "unique_together": {("merchant", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(
                fields=["city", "department"], name="idx_merchant_location"
            ),
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(
                fields=["category", "is_active"], name="idx_merchant_category"
            ),
        ),
    ]
