# Generated by Django 4.2.25 on 2026-03-05 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Microcredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="monto solicitado"
                    ),
                ),
                (
                    "amount_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="monto aprobado",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="tasa de interes (%)",
                    ),
                ),
                ("term_days", models.IntegerField(verbose_name="plazo en dias")),
                (
                    "llo_collateral_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="monto colateral LLO",
                    ),
                ),
                (
                    "total_to_repay",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="total a pagar"
                    ),
                ),
                (
                    "amount_repaid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="monto pagado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Solicitado"),
                            ("APPROVED", "Aprobado"),
                            ("DISBURSED", "Desembolsado"),
                            ("ACTIVE", "Activo"),
                            ("PAID", "Pagado"),
                            ("DEFAULTED", "En mora"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "disbursed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de desembolso"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de vencimiento"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de pago completo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "microcredito",
                "verbose_name_plural": "microcreditos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MicrocreditProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Credito Campesino, Credito Comerciante",
                        max_length=100,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descripcion"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="monto minimo"
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="monto maximo"
                    ),
                ),
                (
                    "interest_rate_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje mensual de interes. Ej: 2.5 = 2.5%",
                        max_digits=5,
                        verbose_name="tasa de interes mensual (%)",
                    ),
                ),
                (
                    "term_days",
                    models.IntegerField(
                        help_text="Plazo maximo del credito en dias.",
                        verbose_name="plazo en dias",
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        default=0,
                        help_text="Dias de gracia antes de iniciar cobro de intereses.",
                        verbose_name="dias de gracia",
                    ),
                ),
                (
                    "requires_llo_collateral",
                    models.BooleanField(
                        default=False, verbose_name="requiere colateral en LLO"
                    ),
                ),
                (
                    "llo_collateral_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje del monto que se requiere en LLO como colateral.",
                        max_digits=5,
                        verbose_name="porcentaje de colateral LLO",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "producto de microcredito",
                "verbose_name_plural": "productos de microcredito",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MicrocreditPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="monto"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Pago regular"),
                            ("EARLY", "Pago anticipado"),
                            ("PARTIAL", "Abono parcial"),
                            ("LATE_FEE", "Recargo por mora"),
                        ],
                        default="REGULAR",
                        max_length=10,
                        verbose_name="tipo de pago",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de completado"
                    ),
                ),
                (
                    "microcredit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="microcredit.microcredit",
                        verbose_name="microcredito",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago de microcredito",
                "verbose_name_plural": "pagos de microcredito",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="microcredit",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="microcredits",
                to="microcredit.microcreditproduct",
                verbose_name="producto",
            ),
        ),
        migrations.AddField(
            model_name="microcredit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="microcredits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.CreateModel(
            name="CreditProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credit_score",
                    models.IntegerField(
                        default=0,
                        help_text="Puntaje de 0 a 1000 basado en comportamiento de pagos.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="puntaje crediticio",
                    ),
                ),
                (
                    "max_credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="monto maximo de credito",
                    ),
                ),
                (
                    "total_loans",
                    models.IntegerField(default=0, verbose_name="total de prestamos"),
                ),
                (
                    "active_loans",
                    models.IntegerField(default=0, verbose_name="prestamos activos"),
                ),
                (
                    "total_repaid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="total pagado",
                    ),
                ),
                (
                    "on_time_payments",
                    models.IntegerField(default=0, verbose_name="pagos a tiempo"),
                ),
                (
                    "late_payments",
                    models.IntegerField(default=0, verbose_name="pagos tardios"),
                ),
                (
                    "last_evaluated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ultima evaluacion"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualizacion"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil crediticio",
                "verbose_name_plural": "perfiles crediticios",
            },
        ),
        migrations.AddIndex(
            model_name="microcredit",
            index=models.Index(
                fields=["user", "status"], name="idx_microcredit_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="microcredit",
            index=models.Index(
                fields=["due_date", "status"], name="idx_microcredit_due_status"
            ),
        ),
    ]
