# Generated by Django 4.2.25 on 2026-03-05 19:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USDT", "Tether (USDT)"),
                            ("ETH", "Ethereum (ETH)"),
                            ("BTC", "Bitcoin (BTC)"),
                            ("LLO", "Llanocoin (LLO)"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Criptomoneda",
                    ),
                ),
                (
                    "rate_cop",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Tasa en COP"
                    ),
                ),
                ("source", models.CharField(max_length=100, verbose_name="Fuente")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tasa de Cambio",
                "verbose_name_plural": "Tasas de Cambio",
            },
        ),
        migrations.CreateModel(
            name="LlanocoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Compra"),
                            ("SELL", "Venta"),
                            ("TRANSFER_IN", "Transferencia recibida"),
                            ("TRANSFER_OUT", "Transferencia enviada"),
                            ("REWARD", "Recompensa"),
                            ("STAKE", "Staking"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de transaccion",
                    ),
                ),
                (
                    "amount_llo",
                    models.DecimalField(
                        decimal_places=8, max_digits=18, verbose_name="Cantidad LLO"
                    ),
                ),
                (
                    "amount_cop",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Monto COP"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000"),
                        max_digits=18,
                        verbose_name="Tasa LLO/COP",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash de transaccion",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llanocoin_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaccion Llanocoin",
                "verbose_name_plural": "Transacciones Llanocoin",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CryptoWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USDT", "Tether (USDT)"),
                            ("ETH", "Ethereum (ETH)"),
                            ("BTC", "Bitcoin (BTC)"),
                        ],
                        max_length=10,
                        verbose_name="Criptomoneda",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=18, verbose_name="Cantidad"
                    ),
                ),
                (
                    "destination_address",
                    models.CharField(max_length=255, verbose_name="Direccion destino"),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash de transaccion",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("POLYGON", "Polygon"),
                            ("ETHEREUM", "Ethereum"),
                            ("BSC", "Binance Smart Chain"),
                            ("BITCOIN", "Bitcoin"),
                        ],
                        max_length=20,
                        verbose_name="Red",
                    ),
                ),
                (
                    "cop_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Monto en COP",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Tasa de cambio",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Comision",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retiro Crypto",
                "verbose_name_plural": "Retiros Crypto",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CryptoDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USDT", "Tether (USDT)"),
                            ("ETH", "Ethereum (ETH)"),
                            ("BTC", "Bitcoin (BTC)"),
                        ],
                        max_length=10,
                        verbose_name="Criptomoneda",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=18, verbose_name="Cantidad"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Hash de transaccion"
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("POLYGON", "Polygon"),
                            ("ETHEREUM", "Ethereum"),
                            ("BSC", "Binance Smart Chain"),
                            ("BITCOIN", "Bitcoin"),
                        ],
                        max_length=20,
                        verbose_name="Red",
                    ),
                ),
                (
                    "cop_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Monto en COP",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Tasa de cambio",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("CONFIRMING", "Confirmando"),
                            ("CONFIRMED", "Confirmado"),
                            ("FAILED", "Fallido"),
                            ("CREDITED", "Acreditado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "confirmations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Confirmaciones"
                    ),
                ),
                (
                    "required_confirmations",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Confirmaciones requeridas"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de confirmacion"
                    ),
                ),
                (
                    "credited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de acreditacion"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_deposits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deposito Crypto",
                "verbose_name_plural": "Depositos Crypto",
                "ordering": ["-created_at"],
            },
        ),
    ]
