# Generated by Django 5.1.5 on 2026-04-10 05:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcard",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="virtualcard",
            name="monthly_spent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="virtualcard",
            name="nickname",
            field=models.CharField(blank=True, default="Mi Tarjeta", max_length=50),
        ),
        migrations.AddField(
            model_name="virtualcard",
            name="total_spent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=15
            ),
        ),
        migrations.CreateModel(
            name="VirtualCardTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Compra"),
                            ("REFUND", "Reembolso"),
                            ("TOPUP", "Recarga"),
                            ("FEE", "Comision"),
                        ],
                        default="PURCHASE",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "merchant_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobada"),
                            ("DECLINED", "Rechazada"),
                            ("REVERSED", "Reversada"),
                        ],
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="global_features.virtualcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
