# Generated by Django 4.2.25 on 2026-03-05 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_cop",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="saldo COP",
                    ),
                ),
                (
                    "balance_llo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="saldo LLO",
                    ),
                ),
                (
                    "total_crypto_reserves_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="reservas cripto totales (USD)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "billetera maestra",
                "verbose_name_plural": "billetera maestra",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance_cop",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="saldo COP",
                    ),
                ),
                (
                    "balance_llo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="saldo LLO",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualizacion"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "billetera",
                "verbose_name_plural": "billeteras",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposito"),
                            ("WITHDRAWAL", "Retiro"),
                            ("TRANSFER_IN", "Transferencia recibida"),
                            ("TRANSFER_OUT", "Transferencia enviada"),
                            ("CRYPTO_DEPOSIT", "Deposito cripto"),
                            ("LLO_PURCHASE", "Compra de LLO"),
                            ("LLO_SALE", "Venta de LLO"),
                            ("COMMISSION", "Comision"),
                            ("MICROCREDIT_DISBURSEMENT", "Desembolso de microcredito"),
                            ("MICROCREDIT_PAYMENT", "Pago de microcredito"),
                        ],
                        max_length=25,
                        verbose_name="tipo de transaccion",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("COP", "Peso colombiano"), ("LLO", "LlanoCoin")],
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="saldo despues"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="referencia",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descripcion"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("COMPLETED", "Completada"),
                            ("FAILED", "Fallida"),
                            ("REVERSED", "Reversada"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                        verbose_name="billetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaccion",
                "verbose_name_plural": "transacciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"], name="idx_wallet_created"
                    )
                ],
            },
        ),
    ]
