# Generated by Django 4.2.25 on 2026-03-05 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="numero de telefono"),
                ),
                ("message", models.TextField(verbose_name="mensaje")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Fallido"),
                            ("DELIVERED", "Entregado"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID del proveedor",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="costo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de envio"
                    ),
                ),
            ],
            options={
                "verbose_name": "mensaje SMS",
                "verbose_name_plural": "mensajes SMS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("TRANSFER_RECEIVED", "Transferencia recibida"),
                            ("TRANSFER_SENT", "Transferencia enviada"),
                            ("DEPOSIT_CONFIRMED", "Deposito confirmado"),
                            ("WITHDRAWAL_PROCESSED", "Retiro procesado"),
                            ("OTP_CODE", "Codigo OTP"),
                            ("LOAN_APPROVED", "Prestamo aprobado"),
                            ("LOAN_PAYMENT_DUE", "Pago de prestamo pendiente"),
                            ("MERCHANT_PAYMENT", "Pago a comerciante"),
                            ("LLO_REWARD", "Recompensa LLO"),
                            ("SYSTEM_ALERT", "Alerta del sistema"),
                            ("PROMOTION", "Promocion"),
                        ],
                        max_length=25,
                        verbose_name="tipo de notificacion",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titulo")),
                ("message", models.TextField(verbose_name="mensaje")),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos adicionales"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push"),
                            ("SMS", "SMS"),
                            ("WEBSOCKET", "WebSocket"),
                            ("EMAIL", "Email"),
                        ],
                        default="PUSH",
                        max_length=10,
                        verbose_name="canal",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="leida")),
                ("is_sent", models.BooleanField(default=False, verbose_name="enviada")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de envio"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de lectura"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificacion",
                "verbose_name_plural": "notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"], name="idx_notification_user_read"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=500, verbose_name="token del dispositivo"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                            ("WEB", "Web"),
                        ],
                        max_length=10,
                        verbose_name="plataforma",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualizacion"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "token de dispositivo",
                "verbose_name_plural": "tokens de dispositivo",
                "unique_together": {("user", "token")},
            },
        ),
    ]
